name: mivet_app
description: MIVET Sales — Flutter starter (modern UI, Cairo + Almarai fonts)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
    - family: typokar
      fonts:
        - asset: assets/fonts/typokar.ttf
    - family: Wessam
      fonts:
        - asset: assets/fonts/a-arslan-wessam-b.ttf